### ISSUE TITLE
Is the package being maintained?

### ISSUE THREAD

**Issue by lyz-code** [lincolnloop/goodconf#13]
Hi @ipmb I've opened some issues some time ago and got no answer :S, it makes me wonder. Is the package still under maintenance?

**Comment by ipmb** [comment]
Sorry, I wasn't getting notifications on the issues (I am now).

I'll review your issues and respond with some thoughts. In general, the project works great for our use cases and hasn't needed any additional development.

I'm happy to review pull requests for new feature ideas if you'd like to contribute.
