### ISSUE TITLE
Official support for 3.11

### ISSUE THREAD

**Issue by apollo13** [lincolnloop/goodconf#15]
I'd like to see support for 3.11, most likely it is just a matter of adding it to the tests. Finding a supported Django version for the tests is more fun then :D If we were to drop 3.7 as well (EOL in 5 months) we could increase Django for the tests to 4.1. Otherwise we could make the tests conditional somehow. This would be okay to do together with #14. Let me know which approach you'd prefer

**Comment by ipmb** [comment]
I'd be fine introducing something like `tox` to handle the test matrix. It would make running the full test suite locally easier. I'd prefer not to drop Python versions before they are EOL.

**Comment by apollo13** [comment]
Ok, I'll see what I can do about tox. I think I can even support 3.7 and 3.11 with Django if you are open to relaxing the requirement for Django to `>=3.x` so python 3.11 can pick Django 4.1

**Comment by ipmb** [comment]
Fixed in 71d3641242f0a2bfd88ec0c795b8197e85ae7b74

**Comment by apollo13** [comment]
I have added support for 3.11 in #19 (since I already rewrote 90% of test.yml there) without removing 3.7. Tox is a bit harder, for good cache efficiency it is actually better to run the tests as is. Will investigate tox later on, but it is not easy to map nicely from the matrix to a tox env.
