### ISSUE TITLE
Doc incorrect

### ISSUE THREAD

**Issue by mjmare** [lincolnloop/goodconf#2]
Hi, thanks for goodconf!

In the example in the docs a Config object is initialised and assigned to a variable config. However the load method returns nothing. Therefore the config var is None. 

Also in the modified manage.py I had to include this line for it to work normally:
```
if __name__ == '__main__':
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'main.settings')
    settings.config.django_manage()
```

**Comment by ipmb** [comment]
Thanks for the report and PR. I took a slightly different approach, but this is fixed now.
