### ISSUE TITLE
Generate comments when writing toml files

### ISSUE THREAD

**Issue by ipmb** [lincolnloop/goodconf#20]
When you generate a yaml config, the docstring and description for each field will be used as comments in the file. https://github.com/lincolnloop/goodconf/blob/188d1fbf6ca224ce77350f50219760beb2949c59/goodconf/__init__.py#L149-L155

It looks like [`tomlkit` has the same functionality](https://github.com/sdispater/tomlkit/blob/master/docs/quickstart.rst#writing), so we should use that.

**Comment by apollo13** [comment]
Will do.
