### ISSUE TITLE
Replace pre-commit workflow with pre-commit.ci

### ISSUE THREAD

**Issue by apollo13** [lincolnloop/goodconf#24]
The pre-commit github action is deprecated… Would you mind setting up https://pre-commit.ci instead? Once done we can delete the pre-commit workflow.

**Comment by apollo13** [comment]
If pre-commit.ci requires to many permissions, I'd at least add caching as described by @tobiasmcnulty in https://tobiasmcnulty.com/posts/caching-pre-commit/

**Comment by ipmb** [comment]
![image](https://user-images.githubusercontent.com/319156/211339339-a0c7f12d-5e97-4b93-b969-286948e4d467.png)

If you want to add the badge, the code is:

```markdown
[![pre-commit.ci status](https://results.pre-commit.ci/badge/github/lincolnloop/goodconf/main.svg)](https://results.pre-commit.ci/latest/github/lincolnloop/goodconf/main)
```
