### ISSUE TITLE
Release 2.1.0

### ISSUE THREAD

**Issue by ipmb** [lincolnloop/goodconf#29]
* [x] update `CHANGES.rst` (can be converted to markdown if desired) (@apollo13)
* [x] Remove zest.releaser (@ipmb)
* [x] Bump version and tag (@ipmb)
* [x] Use `hatch` to build/publish (@ipmb)
* [x] Bump version to dev (@ipmb)
* [x] Document release process (@ipmb)

**Comment by apollo13** [comment]
I will update the `CHANGES.rst` over the weekend. As far as bumping version is concerned, you might wanna look into https://github.com/frankie567/hatch-regex-commit

**Comment by apollo13** [comment]
Btw the description of the repo could get updated to include "toml" :)

**Comment by ipmb** [comment]
Released as `3.0.0` instead because of backwards incompatibilities (Python 3.6 support "removed")

**Comment by apollo13** [comment]
And I was able to confirm the wheel checksum by locally building it and it resulted in the same wheel :partying_face:
