### ISSUE TITLE
Setting `Field(default=None)` results in a `pydantic` error

### ISSUE THREAD

**Issue by inostia** [lincolnloop/goodconf#38]
## Version
```
goodconf==3.0.1
pydantic==1.10.11
```

## Issue
There is [a bug](https://github.com/pydantic/pydantic/issues/6080) present in `pydantic<2` which makes it impossible to use a `None` value in a pydantic dataclass. I believe this is causing an issue when creating a configuration `Field` with `default=None` like so, resulting in the following error:

```
# config.py
class AppConfig(GoodConf):
  FOO  = Field(default=None, help="foo")

...
File "/my/config.py", line 11, in <module>
    class AppConfig(GoodConf):
  File "pydantic/main.py", line 221, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 546, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 578, in pydantic.fields.ModelField._set_default_and_type
pydantic.errors.ConfigError: unable to infer type for attribute "FOO"
```

## Potential Fix
The [fix seems to be to upgrade to `pydantic>2`](https://github.com/pydantic/pydantic/issues/6080#issuecomment-1587113878). The `goodconf` package [lists a requirement of `pydantic<2`](https://github.com/lincolnloop/goodconf/blob/c43b9196b7b068b08e007e56ac6322419827bc48/pyproject.toml#L25).

**Comment by ipmb** [comment]
Pydantic 2 is not compatible with v1 and requires extensive changes. We have a PR open for the upgrade (#36), but it is not complete.

**Comment by ipmb** [comment]
A possible workaround would be to set the default to an empty string (`""`) and use logic to convert it to `None` if needed. For example:

```python
FOO = config.FOO or None
```

**Comment by inostia** [comment]
Thanks for the workaround, @ipmb . Feel free to close this ticket if you think it should be closed, since you are already looking into the Pydantic upgrade.
