### ISSUE TITLE
Deprecation Warning depending on ruamel version

### ISSUE THREAD

**Issue by jonans** [lincolnloop/goodconf#8]
Thanks for this module , super useful quickly making configs.

So nothing is broken just getting deprecation warnings when running code under pytest. I get the following:

PendingDeprecationWarning:      safe_load will be removed, use

  yaml=YAML(typ='safe', pure=True)
  yaml.load(...)

Maybe can do setup based based on ruamel version ? Details in project description: https://pypi.org/project/ruamel.yaml/

Also unrelated,   if none of the "default_files" are found there is no error and FileNotFoundError is not  thrown, is that intended ?

**Comment by dougscc** [comment]
I'm getting the same warnings:

```bash
tests/test_foo.py::test_paths_created
tests/test_foo.py::test_paths_created
tests/test_foo.py::test_yaml
tests/test_foo.py::test_yaml
  /home/somehuman/Projects/thing-im-testing/pro_ject/skeleton.py:39: PendingDeprecationWarning:
  dump will be removed, use

    yaml=YAML(typ='unsafe', pure=True)
    yaml.dump(...)

  instead
    yaml_text = yaml.dump(model_dict, Dumper=yaml.RoundTripDumper)

tests/test_foo.py::test_paths_created
tests/test_foo.py::test_paths_created
tests/test_foo.py::test_yaml
tests/test_foo.py::test_yaml
  /home/somehuman/Projects/thing-im-testing/.direnv/python-venv-3.8.11/lib/python3.8/site-packages/ruamel/yaml/main.py:1364: PendingDeprecationWarning:
  dump_all will be removed, use

    yaml=YAML(typ='unsafe', pure=True)
    yaml.dump_all(...)

  instead
    return dump_all(
```

Nothing appears to be *actually* wrong.

**Comment by lyz-code** [comment]
Maybe migrating to the community maintained [ruyaml fork](https://github.com/pycontribs/ruyaml) solves it
